sonar.verbose=true
sonar.organization=saidamy01
sonar.projectKey=saidemy01_spoovimykey
sonar.projectName=spoovimykey
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

